### ISSUE TITLE
File.delete() and File.deleteSync() throw exception when target is unix socket

### ISSUE THREAD

**Issue by rokya** [dart-lang/io#60]
Steps to reproduce

1. Create a socket file
```shell
nc -vklU test.socket
```
<Ctrl + C> to stop the server
ls result `srwxr-x---  1 rokya primarygroup    0 Sep 26 13:27 test.socket`

2. Run the dart code

rm.dart
```dart
import 'dart:io';

void main() async {
  final file = File('test.socket');
  if (file.existsSync()) {
    print("File is existing.");
    // Neither sync nor async works.
    file.deleteSync();
    // await file.delete();
    print("File is deleted.");
  } else {
    print("File is not existing.");
  }
}
```

`file.deleteSync();` shows:
```
File is existing.
Unhandled exception:
FileSystemException: Cannot delete file, path = 'test.socket' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:455:47)
#3      main (file:///.../home/rokya/test/dart_test/rm.dart:7:10)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

`file.delete();` shows:
```
File is existing.
Unhandled exception:
FileSystemException: Cannot delete file, path = 'test.socket' (OS Error: No such file or directory, errno = 2)
#0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:283:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#6      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#9      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

P.S. I can delete the socket file by `rm test.socket` with terminal.

**Comment by jtmcdole** [comment]
I hit this problem as well. My work around:

```
 await Process.run('/usr/bin/unlink', ['/tmp/fu.sock']);
 ```
